version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dictionary
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: 
      context:  .
    ports:
      - "8000:8000"
    command: ["sh","./start.sh"]
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata:
