# Generated by Django 4.2.13 on 2024-06-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='word',
            name='example_sentences',
        ),
        migrations.AddField(
            model_name='word',
            name='definition_data',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
