# Generated by Django 4.2.13 on 2024-06-25 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_app', '0002_searchhistory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='user',
        ),
    ]
